<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>OAuth2.0 Client</title>

    <?php include 'partials/styles.phtml' ?>
</head>

<body>
    <?php include 'partials/navbar.phtml' ?>

    <div class="container">
        <h3>Client Credentials</h3>

        <?php if ($error): ?>
            <div class="alert alert-danger">
                <?php echo $error ?>
            </div>
        <?php endif ?>

        <h4>Response</h4>
        <pre><?php echo $rawBody ?></pre>

        <?php if (isset($data['access_token'])): ?>
            <h4>Access token</h4>
            <div class="alert alert-success">
                <?php echo $data['access_token'] ?>
            </div>

            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#list">List articles</a></li>
                <li><a data-toggle="tab" href="#get">Get article</a></li>
            </ul>

            <div class="tab-content">
                <div id="list" class="tab-pane fade in active">
                    <h3>List articles</h3>

                    <form action="/resource" method="get">
                        <label for="category">Category</label>
                        <input type="text" name="category" id="category"><br>
                        <label for="prefecture">Prefecture</label>
                        <input type="text" name="prefecture" id="prefecture"><br>
                        <label for="offset">Offset</label>
                        <input type="text" name="offset" id="offset"><br>
                        <label for="limit">Limit</label>
                        <input type="text" name="limit" id="limit"><br><br>

                        <label for="access_token">Access token</label>
                        <input type="text" name="access_token" value="<?php echo $data['access_token'] ?>"><br><br>

                        <button type="submit" class="btn btn-primary">Get articles</button>
                    </form>
                </div>
                <div id="get" class="tab-pane fade">
                    <h3>Get article</h3>

                    <form action="/resource" method="get">
                        <label for="article_id">Article ID</label>
                        <input type="text" name="article_id" id="article_id"><br><br>

                        <label for="access_token">Access token</label>
                        <input type="text" name="access_token" value="<?php echo $data['access_token'] ?>"><br><br>

                        <button type="submit" class="btn btn-primary">Get article</button>
                    </form>
                </div>
            </div>
        <?php endif ?>

        <hr>

        <p><a href="/">Back</a></p>
    </div>

    <?php include 'partials/scripts.phtml' ?>
</body>
</html>
