<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>OAuth2.0 Client</title>

    <?php include 'partials/styles.phtml' ?>
</head>

<body>
    <?php include 'partials/navbar.phtml' ?>

    <div class="container">
        <h2>Error</h2>

        <div class="well"><?= htmlspecialchars($error) ?></div>

        <h3>Response</h3>

        <div class="well"><?= nl2br(htmlspecialchars($body)) ?></div>

        <hr>

        <p><a href="/">Back</a></p>
    </div>

    <?php include 'partials/scripts.phtml' ?>
</body>
</html>
