<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>OAuth2.0 Client</title>

    <?php include 'partials/styles.phtml' ?>
</head>

<body>
    <?php include 'partials/navbar.phtml' ?>

    <div class="container">
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#authorize">Authorize</a></li>
            <li><a data-toggle="tab" href="#credentials">Client Credentials</a></li>
            <li><a data-toggle="tab" href="#refresh">Refresh Token</a></li>
        </ul>

        <div class="tab-content">
            <div id="authorize" class="tab-pane fade in active">
                <h3>Authorize</h3>
                <p>Click below to initiate authorization:</p>
                <p><a href="/authorize" class="btn btn-primary">Authorize</a></p>
            </div>
            <div id="credentials" class="tab-pane fade">
                <h3>Client Credentials</h3>
                <p>Click below to get access token with client credentials:</p>
                <form action="/client_credentials" method="post">
                    <label for="client_id">Client ID</label>
                    <input type="text" name="client_id" id="client_id" value="<?php echo $settings['client_id'] ?>">
                    <label for="client_secret">Client secret</label>
                    <input type="text" name="client_secret" id="client_secret" value="<?php echo $settings['client_secret'] ?>"><br>

                    <button type="submit" class="btn btn-primary">Get access token</button>
                </form>
            </div>
            <div id="refresh" class="tab-pane fade">
                <h3>Refresh Token</h3>
                <p>Click below to get new access token with refresh token:</p>
                <p><a href="/refresh_token" class="btn btn-primary">Get access token</a></p>
            </div>
        </div>
    </div>

    <?php include 'partials/scripts.phtml' ?>
</body>
</html>
