<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>OAuth2.0 Client</title>

    <?php include 'partials/styles.phtml' ?>
</head>

<body>
    <?php include 'partials/navbar.phtml' ?>

    <div class="container">
        <h3>Resource</h3>

        <?php if ($error): ?>
            <div class="alert alert-danger">
                <?php echo $error ?>
            </div>
        <?php endif ?>

        <h4>Json</h4>
        <pre style="height: 300px; overflow: scroll"><?php echo $json ?></pre>

        <h4>Response</h4>
        <pre><?php echo $rawBody ?></pre>

        <p><a href="/">Back</a></p>
    </div>

    <?php include 'partials/scripts.phtml' ?>
</body>
</html>
